[package]
name = "rpc_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc_lib = { path = "../rpc_lib" }
rpc_interface = { path = "../rpc_interface" }
